Add item requests
89219339769/java-shareit pull request #13
Opened 2023-01-10 10:34 UTC by 89219339769

2023-01-10 21:24 UTC, sergeymamonov requested changes

2023-01-10 21:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<ItemDtoShort> itemsShort = new ArrayList<>();
Лишняя переменная.

2023-01-10 21:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findItemByRequestId(Long requestId);
Этот метод нигде не используется.

2023-01-10 21:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public User() {
@NoArgsConstructor

2023-01-10 21:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/Validator.java
> +//import ru.practicum.shareit.exceptions.*;
В проекте не должно быть закомментированных строчек кода

2023-01-10 21:24 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/ItemTests/ItemIntegralTests.java
> +     //   ItemDtoForBooker(id=1, name=name, description=description, available=true, ownerId=2, requestId=0, lastBooking=null, nextBooking=null, comments=[])
В проекте не должно быть закомментированных строчек кода

2023-01-11 07:33 UTC, 89219339769 commented on pom.xml
> +			<artifactId>spring-data-jpa</artifactId>
+

2023-01-11 07:35 UTC, 89219339769 commented on pom.xml
> +			<artifactId>postgresql</artifactId>
+

2023-01-11 07:38 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0) {
v

2023-01-11 07:41 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        ItemDtoShort temDtoShort = itemMapper.itemToItemShort(item);
v

2023-01-11 07:44 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            commentDtoOutList.add(commentMapper.toCommentDt0FromComment(comment));
v

2023-01-11 07:47 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<ItemDtoShort> itemsShort = new ArrayList<>();
v

2023-01-11 07:53 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findItemByRequestId(Long requestId);
v

2023-01-11 07:54 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public User() {
v

2023-01-11 07:55 UTC, 89219339769 commented on src/test/java/ru/practicum/shareit/ItemTests/ItemIntegralTests.java
> +     //   ItemDtoForBooker(id=1, name=name, description=description, available=true, ownerId=2, requestId=0, lastBooking=null, nextBooking=null, comments=[])
v

2023-01-11 19:21 UTC, sergeymamonov approved these changes

2023-01-11 19:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
Если size равен 0, то это тоже некорректное значение.

2023-01-11 19:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            ItemDtoForOwner itemDtoForOwner = itemMapper.toItemDtoForOwner(itemFromDb1, last, next, commentDtoOutList);
return ItemMapper.toItemDtoForOwner(itemFromDb1, last, next, commentDtoOutList);

В строке 121 по аналогии.

2023-02-16 14:44 UTC, merged