Add docker
89219339769/java-shareit pull request #14
Opened 2023-01-27 13:29 UTC by 89219339769

2023-01-30 20:54 UTC, sergeymamonov requested changes

2023-01-30 20:54 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/exceptions/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Где используется это исключение?

2023-01-30 20:54 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse objectWrongEnterExeption(final NotFoundException e) {
Где может произойти такая ошибка?

2023-01-30 20:54 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public BookingClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder) {
Лучше подобные литералы выделять в ресурсные файлы или константы.

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (item.getAvailable() == false) {
Можно проще if (!item.getAvailable())

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
Для валидации есть сервис gateway, здесь никакой валидации входных данных уже быть не должно.

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
Лишняя валидация

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/exceptions/EmptyItemDescriptionException.java
> +    public EmptyItemDescriptionException(String message) {
Это исключение где-то используется?

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +public class ErrorHandler {
Проверить, все ли методы здесь нужны?

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/exceptions/IncorrectEmailException.java
> +public class IncorrectEmailException extends RuntimeException {
Это исключение где-то используется?

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/exceptions/NoEmailException.java
> +public class NoEmailException extends RuntimeException {
Валидация в сервисе gateway

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/exceptions/NoItemNameException.java
> +public class NoItemNameException extends RuntimeException {
Валидация в сервисе gateway

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Booking lastBooking = bookingListbyUserOwner.stream()
Сложность можно упростить, есть до цикла сделать предобработку данных и создать мапу, где ключ это айдишник, а значение - это бронирование. Одну мапу для последних бронирований, вторую - для следующих.

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    .sorted((o2, o1) -> {
Сложность сортировки - это О(Nlog(N)), поиска минимума - это О(N)

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(element -> itemMapper.itemToItemShort(element))
Не нужно обращаться к статическому методу через экземпляр класса.

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +    public static RequestDtoForTest toItemRequestDtoForTest(RequestDto requestDto) {
Что это за метод? Специальных методов для тестов в основном коде быть не должно.

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +    public static RequestDtoForTest toItemRequestDtoForTest(RequestDto requestDto) {
Что это за метод? Специальных методов для тестов в основном коде быть не должно.

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/request/RequestDtoForTest.java
> +public class RequestDtoForTest {
В коде не должно быть никаких классов для тестов.

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/Validator.java
> +public class Validator {
Валидация в сервисе gateway

2023-01-30 20:54 UTC, sergeymamonov commented on server/src/main/resources/schema.sql
> +--DELETE  FROM items;
А зачем здесь закомментированный код?

2023-01-31 06:41 UTC, 89219339769 commented on gateway/src/main/java/ru/practicum/shareit/exceptions/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
+

2023-01-31 06:41 UTC, 89219339769 commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse objectWrongEnterExeption(final NotFoundException e) {
+

2023-01-31 07:02 UTC, 89219339769 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public BookingClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder) {
+

2023-01-31 07:04 UTC, 89219339769 commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (item.getAvailable() == false) {
+

2023-01-31 07:14 UTC, 89219339769 commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
+

2023-01-31 07:16 UTC, 89219339769 commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +    public static RequestDtoForTest toItemRequestDtoForTest(RequestDto requestDto) {
+

2023-01-31 07:18 UTC, 89219339769 commented on server/src/main/java/ru/practicum/shareit/request/RequestDtoForTest.java
> +public class RequestDtoForTest {
+

2023-01-31 07:20 UTC, 89219339769 commented on server/src/main/resources/schema.sql
> +--DELETE  FROM items;
+

2023-01-31 07:26 UTC, 89219339769 commented on server/src/main/java/ru/practicum/shareit/Validator.java
> +public class Validator {
+

2023-02-01 09:57 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/exceptions/EmptyItemDescriptionException.java
> +    public EmptyItemDescriptionException(String message) {
Не нахожу в коде, где бы вызывалось это исключение

2023-02-01 09:59 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(element -> itemMapper.itemToItemShort(element))
Исправить

2023-02-01 10:02 UTC, sergeymamonov approved these changes
Не все замечания устранены. Проверьте замечания, относящиеся к исключениям в модуле shareit-server. Сейчас в пакете exception есть лишние иключения, которые не выбрасываются в коде. Эти же лишние исключения задействованы в обработчике ошибок. Классы исключений нужно удалить, обработчик почистить. Смотри замечания, которые давал на первом ревью.

2023-02-16 14:44 UTC, merged