Add controllers
89219339769/java-shareit pull request #5
Opened 2022-12-09 09:19 UTC by 89219339769

2022-12-09 20:15 UTC, sergeymamonov requested changes

2022-12-09 20:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/validation/EmptyDescription.java
> +public class EmptyDescription implements ItemValidation {
А почему нельзя сделать один класс Validator и в нем собрать все эти методы валидации?

2022-12-09 20:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/validation/EmptyDescription.java
> +public class EmptyDescription implements ItemValidation {
А почему нельзя сделать один класс Validator и в нем собрать все эти методы валидации?

2022-12-09 20:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/validation/UserNotFound.java
> +        if (userExist == false) throw new NotFoundException("юзера с таким номером нет");
Можно проще if (userExist)

2022-12-09 20:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +                if (itemFind == false) {
Можно проще if (itemFind) {

2022-12-10 08:02 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/validation/EmptyDescription.java
> +public class EmptyDescription implements ItemValidation {
Переделал, собрал все методы в класс Validator, но нам говорили что у такого подхода есть недостаток, т.к. если придется добавлять новую валидацию тогда придется менять код в методах где требуется валидация. А при моем варианте достаточно создать новый класс и менять существующий код не нужно

2022-12-11 04:49 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/validation/EmptyDescription.java
> +public class EmptyDescription implements ItemValidation {
Не очень понимаю, почему придется менять код. Ведь у вас сейчас есть методы на валидацию каждого отдельного вопроса, например, валидация почты, валидация описания. И каждый этот метод обособлен. То есть если нам потребуется еще валидировать, например, какой-либо объект, то мы просто добавим еще один метод. Но что сейчас можно улучшить с валидатором, так как 1. разделить на валидаторы по сущностям. То есть один валидатор каждой сущности. Вот как у вас разделено по пакетам, так же должны быть разделены валидаторы. То есть один валидатор можно было бы оставить, когда проект маленький. Чем больше проект и больше сущностей, тем больше валидатором.
2. Убрать запрос в БД из валадатора. Посмотрите про принцип единой ответственности в SOLID. То есть класс валидатора должен только валидировать, а не обращаться куда-то. То есть нужно было бы сделать запрос в сервисе и передать данные для валидации в валидатор.

Что касается изменений то посмотрите принцип открытости для добавлений и закрытости для изменений. Нужно проектировать так, чтобы можно было легко добавлять новую логику (в вашем случае это добавление новых методов валидации).

2022-12-11 05:09 UTC, sergeymamonov approved these changes

2022-12-11 05:09 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +                throw new EmailWrongException("адрес указанной обновляемой электронной почты уже сущетсвует ");
Можно делать одну строку без скобок. Но в этом есть опасность, что все привыкли, что if всегда со скобками, и кто-то допишет свой код перед вашей строкой throw new ... и не проверит скобки и потом должно будет разбираться в чем дело. Поэтому лучше ставить скобки даже для одной строки.

2022-12-11 05:09 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            repository.getUsers().get(Math.toIntExact(id) - 1);
Почему так сложно, почему нельзя проще  if (....get(id) == null) {ошибка}
?

IndexOutOfBoundsException - это не подходящая ошибка для данного случая, здесь нужно кинуть, что UserNotFound, она точнее определяет ситуацию.

2022-12-11 05:09 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            validator.validateNoEmail(user);
Много методов валидации, лучше сделать один метод, который отправляет на метод валидации пользователя в валидатор. А уже в этом методе будут подметоды, как перечислено здесь.

2022-12-11 07:48 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/validation/EmptyDescription.java
> +public class EmptyDescription implements ItemValidation {
Спасибо за подсказку, обязательно скорректирую валидацию  к следующему спринту. Под изменением кода я подразумевал добавление нового (если потребуется добавить новую валидацию) метода в класс UserService (  validator.validate...(user);)

2023-02-16 14:44 UTC, merged