Add bookings
89219339769/java-shareit pull request #6
Opened 2022-12-26 13:27 UTC by 89219339769

2022-12-27 11:42 UTC, sergeymamonov requested changes

2022-12-27 11:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : itemsList) {
Здесь в цикле идут запросы к БД. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети. Как в данной ситуации можно уйти от цикла:

Выгружаем комментарии, группируем их по вещам и конвертируем в dto
Выгружаем подтвержденные бронирования отсортированные по дате начала и группируем их по вещам
Для каждой вещи находим последнее и следующее бронирование, а также комментарии и формируем результат

2022-12-27 11:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<ItemDtoShort> itemsShort = new ArrayList<>();
Можно сразу вернуть пустой массив без создания лишней переменной.

2022-12-27 11:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Item> allItems = itemRepository.findAll();
А зачем фильтрацию делаете на стороне приложения? Пример, у пользователя 5 вещей, а из БД выгружается несколько миллионов записей и потом фильтруется на стороне приложения. В итоге все это работает очень медленно

2022-12-27 11:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        List<User> users = repository.findAll();
Эти две строки зачем здесь?

2022-12-27 11:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User user = repository.findById(id)
Не обязательно создавать переменную user.

2022-12-27 11:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User user = repository.findById(id)
Не обязательно создавать переменную user.

2022-12-27 11:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        for (int j = 0; j < repository.findAll().size(); j++) {
Чтобы найти что-то одно в БД, не нужно ворошить всю БД. Для этого нужно сделать определенный запрос в БД select ... where user.email = email

2022-12-27 17:08 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Item> allItems = itemRepository.findAll();
исправлено

2022-12-27 17:11 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        List<User> users = repository.findAll();
исправлено

2022-12-27 17:14 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User user = repository.findById(id)
исправлено

2022-12-27 17:14 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User user = repository.findById(id)
исправлено

2022-12-27 17:18 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<ItemDtoShort> itemsShort = new ArrayList<>();
не разобрался в комментарии, как  можно вернуть что-то пустое, предварительно не создав?

2022-12-27 17:37 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        for (int j = 0; j < repository.findAll().size(); j++) {
исправлено

2022-12-27 21:34 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : itemsList) {
Идею понял, полдня сидел, но реализовать не смог (даже с наводками ревьюера), слишком сложно для меня

2022-12-29 06:14 UTC, sergeymamonov approved these changes

2022-12-29 06:14 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            commentDtoOutList = commentListbyUser.stream()
Поиск в массиве в худшем случае выполняется за длину массива. Поэтому временная сложность такого решения квадратичная. Чтобы уменьшить сложность, можно сделать группировку комментариев и сделать мапу<id, массив комментариев для этого id>. И тогда поиск нужных комментариев для вещи будет занимать O(1).

2022-12-29 06:14 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<ItemDtoShort> itemsShort = new ArrayList<>();
if (query.isBlank()) {
   return new ArrayList<>();
}
Но тут можно еще подумать над логикой, не нужно ли кинуть какую-то ошибку.

2022-12-29 07:11 UTC, 89219339769 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            commentDtoOutList = commentListbyUser.stream()
Спасибо, попробую

2023-02-16 14:44 UTC, merged